import Head from 'next/head'
import { ChangeEventHandler, FormEventHandler, useState } from 'react';
import { createShortLink } from '../lib/createShortLink';

export default function Home() {

  const [url, setUrl] = useState<string | null>(null);

  const shorten = () => {
    if (url !== null) {
      createShortLink(url);
    }
  }

  const updateUrl = (event: React.FormEvent<HTMLInputElement>) => {
    setUrl(event.currentTarget.value);
  }

  return (
    <div>
      <Head>
        <title>lnk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <div className="w-11/12 md:w-8/12 lg:w-4/12 mx-auto mt-8 md:mt-16 lg:mt-36">
          <h1 className="text-6xl text-center">LnK</h1>
          <h2 className="text-lg my-8">Got a long link? We&apos;ll take care of that.</h2>

          <div className="w-full bg-gray-200 shadow-md p-8">
            <form className="flex flex-col">
              <label htmlFor="url-input">Your URL</label>
              <input value={url ?? ''} onChange={updateUrl} name="url-input" id="url-input" type="text" />

              <div className="flex flex-row w-max mx-auto mt-8">
                <button onClick={shorten} type="button" className="bg-purple mr-0.5 px-3 py-2 rounded-tl-md rounded-bl-md transform -skew-x-6 text-white">Shorten</button>
                <button type="button" className="bg-violet ml-0.5 px-3 py-2 rounded-tr-md rounded-br-md transform -skew-x-6 text-white">&amp; Copy</button>
              </div>
            </form>
          </div>

        </div>

      </main>

      <footer>
      </footer>
    </div>
  )
}
