import Head from 'next/head'
import { ChangeEventHandler, FormEventHandler, useState } from 'react';
import { createShortLink } from '../lib/createShortLink';
import Icon from '../components/Icon';
import LoadingIcon from '../components/LoadingIcon';
import UrlInput from '../components/UrlInput';
import ShortLink from '../components/ShortLink';
import ShortenButton from '../components/ShortenButton';
import CopyButton from '../components/CopyButton';

export default function Home() {

  const [url, setUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [shortLink, setShortLink] = useState<string | null>(null);

  const shorten = async () => {
    if (url !== null) {
      setLoading(true);
      const shortLink = await createShortLink(url);
      setShortLink(shortLink);
      setLoading(false);
    }
  }

  const updateUrl = (event: React.FormEvent<HTMLInputElement>) => {
    setUrl(event.currentTarget.value);
  }

  const labelText = !!shortLink ? 'Your New Shortened Url' : 'Your Long Url';

  const formReady = shortLink === null && url !== null;

  return (
    <div>
      <Head>
        <title>lnk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <div className="w-11/12 md:w-8/12 lg:w-4/12 mx-auto mt-8 md:mt-16 lg:mt-36">
          <div className="flex flex-row items-center">
            <div className="mr-2">
              <Icon size="large" />
            </div>
            <h1 className="text-6xl text-center ml-2">LnK</h1>
          </div>
          <h2 className="text-lg my-8">Got a long link? We&apos;ll take care of that.</h2>

          <div className="w-full bg-darkGray bg-opacity-20 shadow-md p-8 rounded-md">
            <form className="flex flex-col">
              <label htmlFor="url-input" className="py-3 text-darkPurple opacity-70">{labelText}</label>

              <div className="h-20 flex items-center justify-center w-full flex-col">
                <UrlInput url={url} updateUrl={updateUrl} hidden={!!(loading || shortLink)} />

                <ShortLink hidden={!shortLink} content={shortLink} />

                <div className="mx-auto">
                  <LoadingIcon show={loading} />
                </div>
              </div>

              <div className="flex flex-row w-max mx-auto mt-8">
                <ShortenButton disabled={!!(shortLink || loading || !url)} onClick={shorten} />
                <CopyButton disabled={!!(loading || !url)} onClick={() => null} />
              </div>
            </form>
          </div>

        </div>

      </main>

      <footer>
      </footer>
    </div>
  )
}
