name: LnK CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  backend-tests:
    name: LnK Backend Tests
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: lnk_platform_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: "1.12"
      - name: Install deps
        run: mix deps.get
        working-directory: ./lnk_platform
      - name: Run tests
        run: mix test
        working-directory: ./lnk_platform

  backend-format-check:
    name: LnK Backend Format Check
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: "1.12"
      - name: Install deps
        run: mix deps.get
        working-directory: ./lnk_platform
      - name: Run format check
        run: mix format --check-formatted
        working-directory: ./lnk_platform

  frontend-tests:
    name: LnK Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn
        working-directory: ./lnk-app
      - name: Run tests
        run: yarn test
        working-directory: ./lnk-app

  frontend-format-check:
    name: LnK Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn
        working-directory: ./lnk-app
      - name: Lint
        run: yarn lint
        working-directory: ./lnk-app
      - name: Typescript
        run: yarn tsc
        working-directory: ./lnk-app
